### ISSUE TITLE
USER STORY: sort a specific category of product

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#10]
As a **customer** I want to be able to **sort a specific category of product** so that I can **find the best priced product on a specific category or sort the products in that category by name**

## Acceptance Criteria

* Users can select a specific category from a dropdown menu.   
* Sorting options include price and product name within the selected category.     
* The product list updates automatically based on the selected sorting option.      
* Users can easily reset the sorting to default. 

## Tasks

- [x] Add a dropdown menu to select product categories.  
- [x] Develop sorting functionality based on price and product name.   
- [x] Incorporate JavaScript to update the product list when sorting options are changed.    
- [x] Create functionality to reset sorting to default settings when the "Sort by" option is clicked

**Comment by alexflip1990** [comment]
This has been completed.
