### ISSUE TITLE
USER STORY: easily select the quantity of a product when purchasing it

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#14]
As a **customer** I want to be able to **easily select the quantity of a product when purchasing it** so that I can **ensure I don't accidentally select the wrong product quantity**

## Acceptance Criteria

* Display quantity input fields for each product.  
* Ensure users can adjust the quantity easily.   

## Tasks

- [x] Add quantity input fields.  
- [x] Enable users to change quantity.   
- [x] Update quantity display instantly.    
- [x] Validate numeric input.

**Comment by alexflip1990** [comment]
This has been completed.
