### ISSUE TITLE
USER STORY: view announcements posted by the site

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#18]
As a **site user** I would like to be able to **view announcements posted by the site** so that I can **attend any cycling events the site does.**

## Acceptance Criteria

* Announcements are visible on the homepage or a dedicated page.   
* Each announcement includes event details like name, date, time, location, and a brief description.  

## Tasks

- [x] Add a section for announcements on the homepage or create a separate announcements page.  
- [x] Create a link for accessing announcements in the profile menu.    
- [x] Display announcements retrieved from the database.

**Comment by alexflip1990** [comment]
This has been completed.
