### ISSUE TITLE
USER STORY: add new products

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#19]
As **User Admin** I would like to be able **to add new products** so that site users and customers can **view and purchase them.**

## Acceptance Criteria

* User admin can input new product details.  
* New products are immediately visible to users.  

## Tasks

- [x] Create a form for adding new products.  
- [x] Connect the form to the database to store product information.     
- [x] Display newly added products on the website.    
- [x] Test to confirm new products appear for users after addition.

**Comment by alexflip1990** [comment]
This has been completed.
