### ISSUE TITLE
USER STORY:  update information on products

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#20]
As **User Admin** I would like to be able to **update information on products** so that **site users and customers can read the new information about the products.**

## Acceptance Criteria

* User admin can edit product details.   
* Product updates are shown on the website.   

## Tasks

- [x] Create a page for user admin to edit products.  
- [x] Enable user admin to save changes to product details.      
- [x] Ensure product information is updated.

**Comment by alexflip1990** [comment]
This has been completed.
