### ISSUE TITLE
USER STORY: remove/delete any products

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#21]
As **User Admin** I would like to **remove/delete any products** so that these **products will not be shown on the site to site users and customers.**

## Acceptance Criteria

* User admin can access the delete option for each product.   
* Deleted products are immediately removed from the website.   

## Tasks

- [x] Implement a delete link for each product visible to user admin.  
- [x] Ensure only user admin can access the delete option.     
- [x] Create functionality to remove products from the database upon deletion.

**Comment by alexflip1990** [comment]
This has been completed.
