### ISSUE TITLE
USER STORY: create a new announcement

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#22]
As **User admin** I would like to be able to **create a new announcement** so that site users can **view the announcement from their profile once logged in.**

## Acceptance Criteria

* User admin can create new announcements.   
* Site users can view announcements after logging in.   

## Tasks

- [x] Create a form for user admin to add announcements.  
- [x] Save announcements to the database.      
- [x] Display announcements on announcements list page.

**Comment by alexflip1990** [comment]
This has been completed.
