### ISSUE TITLE
USER STORY: edit any existing announcement

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#23]
As **User Admin** I would like to be able to **edit any existing announcement** so that any **spelling errors or incorrect information can be changed without deleting the announcement.**

## Acceptance Criteria

* User admin can edit announcements to correct errors or update information.   
 
## Tasks

- [x] Add an edit button for each announcement.  
- [x] Develop a form with existing announcement details for editing.     
- [x] Update announcements in the database upon editing.

**Comment by alexflip1990** [comment]
This has been completed.
