### ISSUE TITLE
USER STORY: delete any announcement

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#24]
As **User Admin** I would like to be able to **delete any announcement** so that **announcements that are no longer relevant are removed from the site.**

## Acceptance Criteria

* User admin can delete announcements that are no longer relevant.   
  
## Tasks

- [x] Add a delete button for each announcement.  
- [x] Implement a confirmation prompt before deleting an announcement.    
- [x] Remove the announcement from the database upon deletion.

**Comment by alexflip1990** [comment]
This has been completed.
