### ISSUE TITLE
USER STORY: provide shipping and payment details easily during the checkout process

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#27]
**As a customer**, I want to be able to **provide my shipping and payment details easily during the checkout process** so that I can **complete my purchase quickly and efficiently.**

## Acceptance Criteria

* Users can easily enter shipping details at checkout.   
* Users can effortlessly enter payment details at checkout.  

## Tasks

- [x] Create simple and clear shipping details input form.  
- [x] Develop straightforward payment details on form.      
- [x] Implement validation to ensure correct input on form.

**Comment by alexflip1990** [comment]
This has been completed.
