### ISSUE TITLE
USER STORY: view the total of my purchases at any time

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#3]
As a **customer** I want to be able to **easily view the total of my purchases at any time** so that I can **avoid spending to much**

## Acceptance Criteria

*  Show the total purchase amount clearly on the checkout page. 
*  Update the total automatically when items are added or removed. 

## Tasks

- [x]  Calculate the total purchase amount.
- [x]  Display the total on the checkout page.
- [x]  Implement automatic updating of the total.

**Comment by alexflip1990** [comment]
This has been completed.
