### ISSUE TITLE
USER STORY: register for an account

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#4]
As a **site user** I want to be able to **easily register for an account** so that I can **have a personal account and be able to view my profile**

## Acceptance Criteria

* Design a simple registration form. 
* Allow users to sign up using their email and password.
* Ensure users email addresses are unique and passwords meet security standards.

## Tasks

- [x]  Create a user-friendly registration form.
- [x]  Add email and password fields.
- [x]  Develop backend functionality for registration.
- [x]  Validate user input for uniqueness and security.
- [x]  Test registration process for functionality and ease of use.

**Comment by alexflip1990** [comment]
This has been completed.
