### ISSUE TITLE
USER STORY: login or logout

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#5]
As a **site user** I want to be able to **easily login or logout** so that I can **access my personal account information** 

## Acceptance Criteria

*  Enable users to log in with their username/email and password. 
*  Include a logout option for users to easily sign out. 

## Tasks

- [x] Create a login form for username/email and password input. 
- [x] Develop the functionality for logging users in.  
- [x] Implement a logout option.  
- [x] Test login and logout features for usability.

**Comment by alexflip1990** [comment]
This has been completed.
