### ISSUE TITLE
USER STORY: sort the list of available products

### ISSUE THREAD

**Issue by alexflip1990** [alexflip1990/ride_on#9]
As a **customer**  I want to be able to **sort the list of available products** so that I can **easily identify the best priced and categorically sorted products**

## Acceptance Criteria

* Users can sort products by price in ascending and descending order.   
* Users can sort products by category to view products within a specific category.      
* Selecting a sorting option updates the displayed products. 

## Tasks

- [x] Implement functionality to sort products by price.  
- [x] Develop functionality to sort products by category.   
- [x] Ensure the sorting option list updates automatically using JavaScript.

**Comment by alexflip1990** [comment]
This has been completed.
